# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Trang Chủ
    url: /
    weight: 10
  - name: Documentation
    url: docs/
    weight: 20
  - name: Jupyter
    url: http://3.95.241.171:8888
    weight: 30
  - name: StackEdit
    url: http://donam.synology.me:1111/
    weight: 40
